name: Build NetIPTV Windows

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) {
            npm ci
          } else {
            npm install
          }

      - name: Build Windows installer
        run: npm run dist
        env:
          # (valfritt) kodsignering via secrets
          CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetIPTV-Windows-Installer
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
          if-no-files-found: warn

      - name: Create GitHub Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.exe
